module.exports = [ "Abuno",
"Acmac-Mariano Badelles Sr",
"Bagong Silang", 
"Bonbonon",
"Bunawan",
"Buru-un",
"Dalipuga",
"Del Carmen",
"Digkilaan",
"Ditucalan",
"Dulag",
"Hinaplanon",
"Hindang",
"Kabacsanan",
"Kalilangan",
"Kiwalan",
"Lanipao",
"Luinab",
"Mahayahay",
"Mainit",
"Mandulog",
"Maria Cristina",
"Pala-o",
"Panoroganan",
"Poblacion",
"Puga-an",
"Rogongon",
"San Miguel",
"San Roque",
"Santa Elena",
"Santa Filomena",
"Santiago",
"Santo Rosario",
"Saray",
"Suarez",
"Tambacan",
"Tibanga",
"Tipanoy",
"Tomas L. Cabili (Tominobo Proper)",
"Tominobo Upper",
"Tubod",
"Ubaldo Laya",
"Upper Hinaplanon",
"Villa Verde" ]